config:
	docker-compose config
build:
	docker-compose build
push:
	docker-compose push
pull:
	docker-compose pull
start:
	docker-compose up -d
stop:
	docker-compose down
restart:
	docker-compose restart
run:
	docker-compose run --rm --entrypoint sh app
logs:
	docker-compose logs -f
ps:
	docker-compose ps
shell:
	docker-compose exec vsftpd bash
user.add:
	sh/user_add.sh tarlouze
	