config:
	docker-compose config
build:
	docker-compose build
push:
	docker-compose push
start:
	docker-compose up -d
stop:
	docker-compose down
restart:
	docker-compose restart
ps:
	docker-compose ps
logs:
	docker-compose logs -f
shell.server:
	docker-compose exec server sh
shell.client:
	docker-compose exec client sh