.PHONY: help
.DEFAULT_GOAL := help

help h: ## Show help
	@awk 'BEGIN {FS = ":.*##"} \
	/^[a-zA-Z0-9_. -]+:.*##/ { \
		split($$1,a," "); \
		printf "%-20s %s\n", a[1], $$2 \
	} \
	/^##@/ {printf "\n%s\n", substr($$0,5)}' $(MAKEFILE_LIST)

build: ## Build
	clang -fobjc-arc -framework Foundation main.m Person.m -o Person

run: ## Run
	./Person