version: '3.7'
services:
  management1:
    container_name: management1
    image: $MYSQL_VERSION
    volumes:
      - ./management/my.cnf:/etc/my.cnf
      - ./management/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      cluster:
        ipv4_address: 192.168.0.2
    command: ndb_mgmd
  ndb1:
    container_name: ndb1
    image: $MYSQL_VERSION
    volumes:
      - ./management/my.cnf:/etc/my.cnf
      - ./management/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      cluster:
        ipv4_address: 192.168.0.3
    command: ndbd
  ndb2:
    container_name: ndb2
    image: $MYSQL_VERSION
    volumes:
      - ./management/my.cnf:/etc/my.cnf
      - ./management/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      cluster:
        ipv4_address: 192.168.0.4
    command: ndbd
  mysql1:
    container_name: mysql1
    image: $MYSQL_VERSION
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cluster
    volumes:
      - ./management/my.cnf:/etc/my.cnf
      - ./management/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    ports: 
      - 3306:3306
    networks:
      cluster:
        ipv4_address: 192.168.0.10
    command: mysqld
networks:
  cluster:
    external:
      name: cluster
    ipam:
      config:
        - subnet: 192.168.0.0/16