config:
	docker-compose config
start:
	docker-compose up -d
stop:
	docker-compose down
restart:
	docker-compose restart
ps:
	docker-compose ps
logs:
	docker-compose logs -f
shell:
	docker-compose exec mysql1 mysql -uroot -proot cluster
mgm:
	docker-compose exec management1 ndb_mgm