services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.busybox
      args:
        BUSYBOX_IMAGE:
  app:
    depends_on:
      - base
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
      dockerfile: Dockerfile.nginx
      args:
        NGINX_IMAGE:
        BASE_IMAGE:
    ports:
      - 80:80
