services:
    nginx:
        image: $NGINX_IMAGE
        volumes:
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./etc/letsencrypt:/etc/letsencrypt
            - ./src/nginx:/var/www/html
        ports:
            - 80:80
            - 443:443
    httpd:
        image: $HTTPD_IMAGE
        build:
            context: .
            dockerfile: Dockerfile.httpd
            args:
                HTTPD_IMAGE:
        volumes:
            - ./etc/httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
            - ./etc/letsencrypt:/etc/letsencrypt
            - ./src/httpd:/var/www/html
        environment:
            - name=value
        ports:
            - 80:80
            - 443:443
