name: Create Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  version-create-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Release version to')
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.event.pull_request.head.ref }}" --generate-notes
