services:
  varnish:
    image: $VARNISH_VERSION
    tmpfs:
      - /var/lib/varnish:exec
    volumes:
      - ./etc/default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - 80:80
    restart: unless-stopped
