services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        PYTHON_IMAGE:
    ports:
      - "8000:8000"
  nginx:
    image: $NGINX_IMAGE
    volumes:
      - ./etc/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
