server {
    listen 80;
    server_name appdemo.name *.appdemo.name;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name appdemo.name *.appdemo.name;

    ssl_certificate /etc/letsencrypt/live/appdemo.name/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/appdemo.name/privkey.pem;

    root /var/www/html;
    index index.html;

    access_log /var/log/nginx/appdemo.name-access.log;
    error_log /var/log/nginx/appdemo.name-error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
