version: '3.7'
services:
  proxy:
    depends_on: 
      - app
    image: nginx:1.17.8-alpine
    volumes: 
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    restart: always
  app:
    build: 
      target: prod
    image: anunca/demo-express-mongodb:prod
    environment:
      NODE_ENV: production
    restart: always
  db:
    restart: always
