name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-26.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set git config user name and email
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email github-actions@github.com        

      - name: Create tag
        run: git tag -a v${{ github.run_number }} -m "Tag created from workflow"

      - name: Push tag
        uses: ad-m/github-push-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Changes in this release:
            ${{ steps.commit_messages.outputs.messages }}
          draft: false
          prerelease: false
