# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provision "shell", path: "sh/provision.sh"

    config.vm.define "k8s-master" do |master|
        master.vm.box = "centos/7"
        master.vm.hostname = "master.k8s.local"
        master.vm.network "private_network", ip: "172.16.0.10"
        master.vm.provider "virtualbox" do |v|
            v.name = "k8s-master"
            v.memory = 4092
            v.cpus = 4
        end
        master.vm.provision "shell", path: "sh/provision_master.sh"
    end

    Workers = 2

    (1..Workers).each do |w|
        config.vm.define "k8s-worker#{w}" do |worker|
            worker.vm.box = "centos/7"
            worker.vm.hostname = "worker#{w}.k8s.local"
            worker.vm.network "private_network", ip: "172.16.0.1#{w}"
            worker.vm.provider "virtualbox" do |v|
                v.name = "k8s-worker#{w}"
                v.memory = 4092
                v.cpus = 4
            end
            worker.vm.provision "shell", path: "sh/provision_worker.sh"
        end
    end
    
end
