version: '3.7'
services:
  app:
    image: anunca/ch:go
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        GO_VERSION:
        ALPINE_VERSION:
    ports: 
      - 80:80
      