services:
  pure-ftpd:
    image: $IMAGE
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OS_IMAGE:
    volumes:
      - './data:/home/ftp'
      - etc:/etc/pure-ftpd
    # ports:
    #   - '20:20'
    #   - '21:21'
    privileged: true
    working_dir: /home/ftp/$USERNAME
    network_mode: host
volumes:
  etc:
