pull:
	docker-compose pull
build:
	docker-compose build
push:
	docker-compose push
start:
	docker-compose up -d
stop:
	docker-compose down
ps:
	docker-compose ps
connect:
	docker-compose exec pure-ftpd bash
user.add:
	USERNAME=tarlouze bash sh/user_add.sh