services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
      args:
        HAPROXY_IMAGE:
    image: $LB_IMAGE
    ports:
      - 80:80
      - 443:443
      - 8080:8080
  nginx1:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        NGINX_IMAGE:
    image: $WEB_IMAGE
    volumes:
      - ./src:/usr/share/nginx/html
  nginx2:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      args:
        NGINX_IMAGE:
    image: $WEB_IMAGE
    volumes:
      - ./src:/usr/share/nginx/html
  app:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
      args:
        PHP_IMAGE:
    image: $APP_IMAGE
