services:
  haproxy:
    image: demo/haproxy:prod
    build:
      target: prod
  nginx1:
    image: demo/haproxy-nginx:prod
    build:
      target: prod
  nginx2:
    image: demo/haproxy-nginx:prod
    build:
      target: prod
  app:
    image: demo/haproxy-php:prod
    build:
      target: prod
