- hosts: master
  become: yes
  tasks:
    - name: install K8S
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> k8s_init.txt
      args:
        chdir: /home/ansible
        creates: k8s_init.txt

    - name: create .kube directory
      become: yes
      become_user: ansible
      file:
        path: /home/ansible/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ansible/.kube/config
        remote_src: yes
        owner: ansible

    - name: install Flannel
      become: yes
      become_user: ansible
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> flannel_init.txt
      args:
        chdir: /home/ansible
        creates: flannel_init.txt

    - name: install bc
      apt:
        name: bc
        state: latest

    #https://kubernetes.github.io/ingress-nginx/deploy/#bare-metal
    #https://kubernetes.github.io/ingress-nginx/deploy/baremetal/
    #https://kubernetes.github.io/ingress-nginx/deploy/#prerequisite-generic-deployment-command
    #If you are using a Kubernetes version previous to 1.14, you need to change kubernetes.io/os to beta.kubernetes.io/os
    - name: install Ingress
      become: yes
      become_user: ansible
      shell: |
        wget https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/mandatory.yaml
        K8S_VERSION=$(kubectl version --short|grep -iserver|cut -d 'v' -f3|cut -d '.' -f1-2)
        [ $(echo "$K8S_VERSION < 1.14" |bc -l)  -eq 1 ] && sed -i 's|kubernetes.io/os|beta.kubernetes.io/os|g' mandatory.yaml
        
        kubectl apply -f mandatory.yaml
        kubectl get pods -n ingress-nginx

        rm mandatory.yaml

        wget https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.30.0/deploy/static/provider/baremetal/service-nodeport.yaml
        K8S_MASTER=`kubectl get nodes -o wide|tail -n3|awk '{print $6}'|sed '1q;d'`
        K8S_WORKER1=`kubectl get nodes -o wide|tail -n3|awk '{print $6}'|sed '2q;d'`
        K8S_WORKER2=`kubectl get nodes -o wide|tail -n3|awk '{print $6}'|sed '3q;d'`
        sed -i "s/type: NodePort/type: LoadBalancer\n  externalIPs:\n    - $K8S_MASTER\n    - $K8S_WORKER1\n    - $K8S_WORKER2\n  externalTrafficPolicy: Local/" service-nodeport.yaml
        
        kubectl apply -f service-nodeport.yaml
        kubectl get services -n ingress-nginx
        
        rm service-nodeport.yaml
      args:
        chdir: /home/ansible