server {
  listen 80;
  listen 443 ssl http2;

  ssl_certificate /etc/nginx/ssl/$APP_DOMAIN_NAME.crt;
  ssl_certificate_key /etc/nginx/ssl/$APP_DOMAIN_NAME.key;

  server_name $APP_DOMAIN_NAME;

  location / {
    add_header Content-Type text/plain;
    return 200 '200';
  }

  error_page 497 https://$host$request_uri;

  if ($scheme = http) {
      return 302 https://$server_name$request_uri;
  }
}
