worker_processes 5;

events { worker_connections 4096; }

http {

    sendfile on;

    gzip on;

    include proxy_params;

    server {
        listen 80;

        server_name localhost;

        location = /health {
            access_log off;
            add_header 'Content-Type' 'application/json';
            return 200 '{"status":"Ok"}';
        }
    }

    server {
        listen 80;

        server_name ###DOMAIN_NAME###;

        return 301 https://$server_name$request_uri;
    }    

    server {
        listen 443 ssl;
        server_name ###DOMAIN_NAME###;

        ssl_certificate /etc/nginx/ssl/###DOMAIN_NAME###.crt;
        ssl_certificate_key /etc/nginx/ssl/###DOMAIN_NAME###.key;

        location / {
            add_header 'Content-Type' 'text/plain';
            return 200 'OK';
        }

        location = /app {
            resolver 127.0.0.11 valid=30s;
            set $app app:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
            fastcgi_pass $app;
        }
    }

    server {
        listen 80;

        server_name www.###DOMAIN_NAME###;

        return 301 https://$server_name$request_uri;
    }    

    server {
        listen 443 ssl;
        server_name www.###DOMAIN_NAME###;

        ssl_certificate /etc/nginx/ssl/###DOMAIN_NAME###.crt;
        ssl_certificate_key /etc/nginx/ssl/###DOMAIN_NAME###.key;

        resolver 127.0.0.11 valid=30s;

        location / {
            set $www http://www;
            proxy_pass $www;
        }
    }

    server {
        listen 80;

        server_name backoffice.###DOMAIN_NAME###;

        return 301 https://$server_name$request_uri;
    }    

    server {
        listen 443 ssl;
        server_name backoffice.###DOMAIN_NAME###;

        ssl_certificate /etc/nginx/ssl/###DOMAIN_NAME###.crt;
        ssl_certificate_key /etc/nginx/ssl/###DOMAIN_NAME###.key;

        resolver 127.0.0.11 valid=30s;

        location / {
            set $backoffice http://backoffice;
            proxy_pass $backoffice;
        }
    }
}
