server {
    listen 80;
    server_name app.app.internal;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.app.internal;

    ssl_certificate /etc/letsencrypt/live/app.app.internal/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.app.internal/privkey.pem;

    include /var/www/certbot/conf/options-ssl-nginx.conf;
    ssl_dhparam /var/www/certbot/conf/ssl-dhparams.pem;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    resolver 127.0.0.11 valid=30s;

    location / {
        set $app http://app;
        proxy_pass $app;
    }
}
