ARG HAPROXY_VERSION

FROM $HAPROXY_VERSION

COPY ./etc/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg

ENV HAPROXY_USER=haproxy

# RUN addgroup -S $HAPROXY_USER\
#   && adduser -S -G $HAPROXY_USER $HAPROXY_USER\
#   && mkdir --parents /var/lib/$HAPROXY_USER\
#   && chown -R $HAPROXY_USER:$HAPROXY_USER /var/lib/$HAPROXY_USER

RUN mkdir --parents /var/lib/$HAPROXY_USER\
  && chown -R $HAPROXY_USER:$HAPROXY_USER /var/lib/$HAPROXY_USER

CMD ["haproxy", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
