plugins:
  - serverless-webpack
  - serverless-offline #serverless-offline needs to be last in the list 

package:
  individually: true

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
  webpack:
    packager: yarn
    webpackConfig: ./aws/node/webpack.config.js
    includeModules: false

service: user-review-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  versionFunction: false
  memorySize: 1024
  stage: ${opt:stage, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  region: eu-west-1
  deploymentBucket: applications.${self:provider.stage}
  cfnRole: ${opt:configrole, ''}
  environment:
    DYNAMODB_TABLE: user-review
    WS_USER_REVIEW_DESKTOP_X_CLIENT_SOURCE: desktop
    WS_USER_REVIEW_DESKTOP_X_API_KEY: desktop

functions:
  - ${file(./function.yml)}