ARG APACHE_VERSION

FROM $APACHE_VERSION

COPY etc/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf

RUN sed -i '\
s|#LoadModule proxy_module modules/mod_proxy.so|LoadModule proxy_module modules/mod_proxy.so|g;\
s|#LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so|LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so|g;\
s|#Include conf/extra/httpd-vhosts.conf|Include conf/extra/httpd-vhosts.conf|g;\
' /usr/local/apache2/conf/httpd.conf
