service: app

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: item

plugins:
  - serverless-offline
  - serverless-openapi-documentation
  
custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000
  documentation: ${file(serverless.doc.yml):documentation}

functions:
  create:
    handler: item/create.create
    events:
      - http:
          path: item
          method: post
          cors: true
          documentation: ${file(serverless.doc.yml):endpoints.createUser}
  list:
    handler: item/list.list
    events:
      - http:
          path: item
          method: get
          cors: true
  get:
    handler: item/get.get
    events:
      - http:
          path: item/{id}
          method: get
          cors: true
  update:
    handler: item/update.update
    events:
      - http:
          path: item/{id}
          method: put
          cors: true
  delete:
    handler: item/delete.delete
    events:
      - http:
          path: item/{id}
          method: delete
          cors: true
