services:
  app:
    build:
      context: .
      target: ${ENV}
      dockerfile: Dockerfile
      args:
        GO_VERSION:
    image: $IMAGE
    ports:
      - 9000:9000
    volumes:
      - ./src:/app
