services:
  app:
    image: $SMALLSTEP_VERSION
    volumes:
      - data:/home/step
    environment:
      - DOCKER_STEPCA_INIT_NAME
      - DOCKER_STEPCA_INIT_DNS_NAMES
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME
      - DOCKER_STEPCA_INIT_PASSWORD
    ports:
      - 9000:9000
  # smallstep:
  #   depends_on:
  #     - app  
  #   image: $IMAGE
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args: 
  #       - SMALLSTEP_VERSION
  #   volumes:
  #     - ./data:/home/step
volumes:
  data:
