version: '3.7'
services:
  web:
    volumes:
      - php_src:/var/www/html
  app:
    build:
      target: prod
    image: anunca/demo:php-prod
    volumes:
      - php_src:/var/www/html
    environment:
      APP_ENV: prod
volumes:
  php_src:
