ARG PHP_VERSION

FROM $PHP_VERSION as phpBase

RUN docker-php-ext-enable opcache

WORKDIR /var/www/html

#dev
FROM phpBase as dev

COPY --from=composer /usr/bin/composer /usr/local/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apk add unzip git\
  && rm -rf /var/cache/apk/

COPY src .

RUN composer install

#build
FROM dev as build

COPY src .

RUN composer install --optimize-autoloader\
  && composer dump-autoload --optimize --classmap-authoritative

#prod
FROM phpBase as prod

COPY --from=build /var/www/html .