pull:
	docker-compose pull
build:
	docker-compose build
push:
	docker-compose push
start:
	docker-compose up -d
stop:
	docker-compose down
ps:
	docker-compose ps
logs:
	docker-compose logs -f
connect:
	docker-compose exec openssh bash