version: '3.7'
services:
  haproxy:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: $DOCKERFILE
      args: 
        HAPROXY_VERSION:
    image: anunca/haproxy
    ports:
      - 80:80