ARG NGINX_IMAGE

FROM $NGINX_IMAGE AS base

FROM base AS dev

FROM base AS prod

COPY etc/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY etc/nginx/certs/ /etc/nginx/certs/

COPY src /usr/share/nginx/html
